---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repositories/danfromtitan-repo.yaml
  - common/configmap-envars-webhook-values.yaml
  - common/helmrelease-envars-webhook.yaml
  - hello/deployment-hello.yaml
  - hello/svc-hello.yaml
  - hello/ingress-hello.yaml
