---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: management
    kustomize.toolkit.fluxcd.io/namespace: kommander-flux
  name: charts.chaos-mesh.org
  namespace: kommander-flux
spec:
  interval: 10m
  timeout: 1m
  url: https://charts.chaos-mesh.org
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaos-mesh
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: chaos-mesh
      sourceRef:
        kind: HelmRepository
        name: charts.chaos-mesh.org
        namespace: kommander-flux
      version: "2.1.3"
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: chaos-mesh
  valuesFrom:
    - kind: ConfigMap
      name: chaos-mesh-2.1.3-d2iq-defaults
  targetNamespace: ${releaseNamespace}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "chaosmesh-dashboard"
  namespace: ${releaseNamespace}
  labels:
    "kommander.d2iq.io/application": "chaosmesh"
data:
  name: "Chaos Mesh"
  dashboardLink: "/dkp/chaosmesh/dashboard"
  version: "2.1.3"
  category: "Security"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaosmesh-dashboard-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- nonResourceURLs:
  - /dkp/chaosmesh/dashboard
  - /dkp/chaosmesh/dashboard/*
  verbs:
  - get
  - head
  - post
  - put
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaosmesh-dashboard-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- nonResourceURLs:
  - /dkp/chaosmesh/dashboard
  - /dkp/chaosmesh/dashboard/*
  verbs:
  - get
  - head
  - post
  - put
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaosmesh-dashboard-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- nonResourceURLs:
  - /dkp/chaosmesh/dashboard
  - /dkp/chaosmesh/dashboard/*
  verbs:
  - get
  - head
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
    kubernetes.io/ingress.class: kommander-traefik
    traefik.ingress.kubernetes.io/router.middlewares: ${releaseNamespace}-stripprefix@kubernetescrd,${releaseNamespace}-forwardauth@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: chaosmesh-dashboard
  namespace: ${releaseNamespace}
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: chaos-dashboard
            port:
              number: 2333
        path: /dkp/chaosmesh/dashboard
        pathType: ImplementationSpecific
