---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: envars-webhook
  namespace: ${projectNamespace}
spec:
  chart:
    spec:
      chart: envars-webhook
      sourceRef:
        kind: HelmRepository
        name: danfromtitan.github.io-envars-from-node-labels
        namespace: ${projectNamespace}
      #version: "2.1.3"
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: envars-webhook
  valuesFrom:
    - kind: ConfigMap
      name: envars-webhook-values
  targetNamespace: ${projectNamespace}
