---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envars-webhook-0.1.6-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    webhook:
      containersAllowed:
        ingester: true
        prober: true
        store-gateway: true
      namespaceSelector: enabled
      namespaceSelectorLabel: envars
      verboseLogs: false