---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: management
    kustomize.toolkit.fluxcd.io/namespace: kommander-flux
  name: danfromtitan.github.io-envars-from-node-labels
  namespace: kommander-flux
spec:
  interval: 10m
  timeout: 1m
  url: "https://danfromtitan.github.io/envars-from-node-labels/"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: envars-webhook
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: envars-webhook
      sourceRef:
        kind: HelmRepository
        name: danfromtitan.github.io-envars-from-node-labels
        namespace: kommander-flux
      version: "0.1.6"
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: envars-webhook
  valuesFrom:
    - kind: ConfigMap
      name: envars-webhook-0.1.6-defaults
  targetNamespace: ${releaseNamespace}